# Color
set-option -sa terminal-overrides ",xterm*:Tc"

# Bindins
set-option -g prefix M-,
## vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

## Fuzzy find directories
bind-key C-f run-shell -b "~/.config/tmux/scripts/fuzzy-find.sh" 

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# does not log in when start tmux
set -g default-command "${SHELL}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @tpm_plugins '           \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-resurrect  \
   sainnhe/tmux-fzf             \
   tmux-plugins/tmux-yank       \
   loichyan/tmux-toggle-popup   \
   tmux-plugins/tmux-continuum  \
'

set -g @resurrect-strategy-nvim 'session'
set -g  @popup-autostart on
set -gF @popup-id-format '#{b:pane_current_path}/{popup_name}'

set -g @continuum-restore on
set -g @continuum-boot on

# Open in same window
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Pop ups
bind -n C-g run "#{@popup-toggle} -w80% -h80% -Ed'##{pane_current_path}' --name=lazygit lazygit"
bind -n C-t run "#{@popup-toggle} -w80% -h80% -Ed'##{pane_current_path}' --name=terminal zsh"
bind -n C-a run "#{@popup-toggle} -w80% -h80% -Ed'##{pane_current_path}' --name=AI zsh -c $AI_AGENT"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
